### ISSUE TITLE
Parou de funcionar, não está conectando com o WHatsapp

### ISSUE THREAD

**Issue by Overx** [ianpbh/WhatsAppBot#1]
Não está salvando as conversas, sabe me dizer se mudou alguma classe no Whastapp Web?

**Comment by ianpbh** [comment]
Provavelmente, como esse projeto foi criado com intuito de aprendizado apenas, eu não darei continuidade a ele. Mas fique livre para dar um fork e fazer as alterações que achar necessárias

**Comment by Overx** [comment]
> Provavelmente, como esse projeto foi criado com intuito de aprendizado apenas, eu não darei continuidade a ele. Mas fique livre para dar um fork e fazer as alterações que achar necessárias

Reparei aqui que alguns ids e classes do web whatsapp foram alterado, caso tenha o source code do antigo "Web whatsapp" para eu comparar localizar e comparar, faço as alterações aqui e atualizo.
